function [collection, inputDataInfo] = TwoPassKymographProcessing_v01(ExperimentFolder, setting)

% INPUT parameters: setting
% setting.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% INPUT files:
% ExperimentTimeStamp.tiff - data collected by the camera, 
%                               1D image in time = matrix of intensities [frame, pixel] 
% ExperimentTimeStamp.txt - file generated by the camera
%                              contains info about the acqusition settings

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% <this deserves some terminology changes?>
% OUTPUT files: 
% 1. data - saved as ExperimentTimeStamp_D.mat
%         - struct containing the processed images 
%   data.Im - processes kymograph - matrix of optical contrast [frame, pixel]
%   data.TemperatureStart - temperature of the CMOS detector at the beggining of the acquisition
%   data.TemperatureEnd - temperature of the CMOS detector at the end of the acquisition
%   data.Dt - temporal length of one frame (s)
%   data.Dx - length of one pixel (um)

% 2. trajectory - saved as ExperimentTimeStamp_T.mat
%               - struct containing characteristics of a trajectory  
%               - it is a matrix of size: parameter sweep number x particle number
%               - all the fields have size: number of found particles in data file (ExperimentTimeStamp)
%   trajectory.N - temporal length of found trajectory [frame]
%   trajectory.D - diffusivity of a particle [um2/s]
%   trajectory.velocity - diffusivity of a particle [um/s]
%   trajectory.iOC - integrated optical contrast of a particle [um]
%   trajectory.STDiOC - standard deviation of iOC along the trajectory [um]
%   trajectory.iOC_profile_x - positions from which iOC was calculated [pixel number]
%   trajectory.iOC_profile_y - normalized profile of sensitivity along channel 

% 3. PARTICLES - saved as ExperimentTimeStamp_P.mat'
%              - struct containing temporal characteristic of a trajectory 
%   PARTICLES.timeFrame - temporal coordinates of found trajectories [frame number]
%   PARTICLES.position - spatial coordinates of found trajectories [pixel number]

%% set default setting 

% related to kymograph reconstruction
if ~isfield(setting.analysis, 'removeBackground_Dark'); setting.analysis.removeBackground_Dark = 'none'; end
if ~isfield(setting.analysis, 'removeBackground_Light_averageX'); setting.analysis.removeBackground_Light_averageX = 'mean'; end % mean, median
if ~isfield(setting.analysis, 'removeBackground_Light_averageT'); setting.analysis.removeBackground_Light_averageT = 'mean'; end % mean, median
if ~isfield(setting.analysis, 'removeBackground_Light_maskX'); setting.analysis.removeBackground_Light_maskX = 'on'; end % on, off
if ~isfield(setting.analysis, 'removeBackground_Light_maskT'); setting.analysis.removeBackground_Light_maskT = 'on'; end % on, off

% related to integrated contrast calculation
if ~isfield(setting.analysis, 'iOCcalculation'); setting.analysis.iOCcalculation = 'integrate negative values'; end

% related to evaluation of trajectory
if ~isfield(setting.analysis, 'trajectoryProperties')
    setting.analysis.trajectoryProperties = {'positionRefined','timeFrame','N','iOC','STDiOC','iOCprofile','D','velocity'}; 
end

% saving and plotting kymograph
if ~isfield(setting.analysis, 'plotKymograph'); setting.analysis.plotKymograph = 'off'; end
if ~isfield(setting.analysis, 'saveKymograph'); setting.analysis.saveKymograph = 'off'; end

%% load dark calibration 
if isnumeric(setting.darkCalibration) == 0
    load(setting.darkCalibration)
end

%% SETTINGS TO NOT CHANGE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[setting.WxSweep, setting.WtSweep] = meshgrid(setting.WxSweep, setting.WtSweep);
setting.WxSweep = setting.WxSweep(:);
setting.WtSweep = setting.WtSweep(:);

%% Expected characteristics of the particle signatures
%span of the gaussian denoising Kernel [pixel] / expected RMS of particle profile
setting.wx = setting.ws; 
%setting.wx = sqrt(setting.ws.^2 + D_input/3); %this can be expected form diffusing particle with known diffusivity D_input

%minimal distance between spots (must be odd number)
meanRMSWidthAfterConvolution = sqrt(setting.wx.^2 + setting.ws.^2);
meanFWHM = 2*sqrt(2*log(2))* meanRMSWidthAfterConvolution;
setting.Wm = floor((meanFWHM - 1)/2)*2+1; 
%setting.Wm = floor((meanFWHM - 1)/2)*4+1; 

%% list of all raw files
ExperimentTimeStamp=findXfiles(ExperimentFolder,'.tiff');

%% create an empty collection
collection = struct;
for j = 1:length(setting.WxSweep)
    for i = 1:length(setting.analysis.trajectoryProperties)
        collection(j).(setting.analysis.trajectoryProperties{i}) = [];
    end
    collection(j).ExperimentTimeStamp = [];
end

%% run kymograph processing for every file
for itest = 1:length(ExperimentTimeStamp)

    tic

    clear data trajectory PARTICLES

    %% load raw data
    data = loadRawData(strcat(ExperimentFolder,ExperimentTimeStamp{itest}), setting.inputDataFormat);
    setting.flowEstimate = setting.flowEstimate_ums/data.Dx*data.Dt;

    %% select time frames
    %data.Im=data.Im(100:400,:);
    
    %% first-pass kymograph reconstruction
    % Estimate dark-signal profile
    if isnumeric(setting.darkCalibration) == 0
        d_x = get_dark_x((data.TemperatureStart + data.TemperatureEnd)/2, Calibration);
    else 
        d_x = setting.darkCalibration;
    end
    
    % Removal of light and dark background, first estimation of the residual
    R1 = data.Im - d_x;
    
     % Matched Filtering for noise reduction
    R1_filt = imgaussfilt(R1,[eps, setting.wx+eps],'FilterSize',[1,2*ceil(3*(setting.wx+eps))+1]);  
    
    % Removal of the remaining drifts, first estimation of particle contrast (kymograph)
    [C1, resultC1] = removeBackground_Light(R1_filt, setting);
    
    %% particle_tracking
    switch setting.trackingMethod

        case 'trackBeforeDetect'

            PARTICLES = trackBeforeDetect(C1, setting);

            for iTrack=1:length(PARTICLES)
            
                PARTICLES(iTrack).I = C1(sub2ind(size(C1), PARTICLES(iTrack).timeFrame, PARTICLES(iTrack).position));
            
            end

        case 'gabClosingTracker'

            setting.Linking.flowEstimate = setting.flowEstimate_ums/data.Dx*data.Dt;

            Tracks = gabClosingTracker(C1, ...
                peakSign=setting.Detection.peakSign,...
                pfa = setting.Detection.pfa, ...
                localOptimumRange = setting.Detection.localOptimumRange, ...
                boarderRange = setting.Detection.boarderRange, ...
                positionRefinementMethod = setting.FeatureExtraction.positionRefinementMethod, ...
                fittingRadius = setting.FeatureExtraction.fittingRadius, ...
                cut_off_distance = setting.Linking.cut_off_distance, ...
                unmatched_penalty_distance = setting.Linking.unmatched_penalty_distance, ...
                flowEstimate = setting.Linking.flowEstimate, ...
                maxPositiveGab = setting.Linking.maxPositiveGab, ...
                maxNegativeGab = setting.Linking.maxNegativeGab, ...
                gab_closing_cut_off_distance = setting.Linking.gab_closing_cut_off_distance, ...
                gab_closing_penalty_distance = setting.Linking.gab_closing_penalty_distance, ...
                minTrackLength = setting.Linking.minTrackLength);

            PARTICLES = struct([]);

            for iTrack=1:Tracks.nTracks
            
                PARTICLES(iTrack).timeFrame = Tracks.frames{iTrack};
                PARTICLES(iTrack).position = Tracks.positions{iTrack};
                PARTICLES(iTrack).positionRefined = Tracks.positions_refined{iTrack};
                PARTICLES(iTrack).I = Tracks.contrasts{iTrack};
            
            end

            % prefiltering the short ones
            relevant = false(1,length(PARTICLES));
            for iTrack = 1:length(relevant)
                if length(PARTICLES(iTrack).timeFrame) > 20
                    relevant(iTrack) = true;
                end
            end

            PARTICLES = PARTICLES(relevant);

    end

    if strcmp(setting.analysis.plotKymograph, 'on')
        plotKymograph(C1, PARTICLES)
    end

    if strcmp(setting.analysis.saveKymograph, 'on')
        data.Im = zeros([size(data.Im) length(setting.WxSweep)]);
    end
    
    %% second-pass kymograph reconstruction, use Wx and Wt Sweep values
    if isempty(PARTICLES) == 0 && not(isempty(setting.WxSweep))
    
        if strcmp(setting.analysis.removeBackground_Light_maskX, 'on')
            Mask = createMask(C1, PARTICLES, 'width estimation from movement & ws', setting);
        else
            %Mask = createMask(C1, PARTICLES, 'negative and positive values', setting);
            Mask = createMask(C1, PARTICLES, 'width estimation from movement & ws & Wx', setting);
            
        end
    
        % Removal of light and dark background, second estimation of the residual
        [R2, resultR2] = removeBackground_Dark(R1, setting, Mask);

        % Matched Gaussian Filtering for noise reduction
        R2_filt = imgaussfilt(R2,[eps, setting.wx+eps],'FilterSize',[1,2*ceil(3*(setting.wx+eps))+1]); 

        setting_0 = setting;
        for iSweep = 1:length(setting.WxSweep)

              setting_0.Wx = setting.WxSweep(iSweep);
              setting_0.Wt = setting.WtSweep(iSweep);

              % Removal of the remaining drifts, first estimation of particle contrast (kymograph)
              [C2, resultC2] = removeBackground_Light(R2_filt, setting_0, Mask);
              %[C2, resultC2] = removeBackground_Light_old(R2_filt, setting_0, Mask);
              
              % evaluate trajectory
              trajectory = evaluateTrajectory (PARTICLES, C2, setting.analysis.trajectoryProperties, setting, data.Dt, data.Dx);

               % collect results
               for i = 1:length(setting.analysis.trajectoryProperties)
                   collection(iSweep).(setting.analysis.trajectoryProperties{i}) = [collection(iSweep).(setting.analysis.trajectoryProperties{i}), trajectory.(setting.analysis.trajectoryProperties{i})];
               end
               for i = 1:length(trajectory.iOC)
                   collection(iSweep).ExperimentTimeStamp{length(collection(iSweep).ExperimentTimeStamp)+1} = ExperimentTimeStamp{itest};
               end

               % if strcmp(setting.analysis.plotKymograph, 'on')
               %      plotKymograph(C2, PARTICLES, trajectory)
               % end
               % 
               % if strcmp(setting.analysis.saveKymograph, 'on')
               %     data.Im(:,:,iSweep) = C2;
               % end

               % disp(iSweep)

        end
    
    end

    %% save
    if strcmp(setting.analysis.saveKymograph, 'on')
        save(strcat(ExperimentFolder,ExperimentTimeStamp{itest},'_D.mat'),'data');
    end

    toc
    disp(strcat(num2str(itest),'/',num2str(length(ExperimentTimeStamp))))

end 

%% add other info to collection
% sweeps legend (names)
for i = 1:length(setting.WxSweep)
    collection(i).SweepLegend = strcat('Wx = ', num2str(setting.WxSweep(i)),', Wt = ', num2str(setting.WtSweep(i)));
end

%% create inputDataInfo
% length of one frame
inputDataInfo.Dt = data.Dt;

% length of one pixel
inputDataInfo.Dx = data.Dx;

% size of the FOV (in pixels)
inputDataInfo.noPixels = size(data.Im,2);

% temporal length of kymograph (in no of frames)
inputDataInfo.noFrames = size(data.Im,1);
  