function EdgesTable = makeEdgeTable(Edges)

    EdgesTable = table( ...
        (1:length(Edges.source_frame)).', ...
        Edges.source_frame, ...
        Edges.source_spot_id, ...
        Edges.target_spot_id, ...
        Edges.jump_distance, ...
        VariableNames=["edge_id", "source_frame", "source_spot_id", "target_spot_id", "jump_distance"] );

end