steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest',
    '--cache-from', 'europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest',
    '.'
  ]
  timeout: 7200s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'matlab-poc-app', '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest', '--region', 'europe-west1', '--allow-unauthenticated', '--memory', '4Gi', '--cpu', '2']

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/matlab-poc-repo/matlab-poc-app:latest'

options:
  diskSizeGb: 40
timeout: 7200s
