steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nsm-streamlit:latest', '-f', 'streamlit/Dockerfile', '.']
images:
- 'gcr.io/$PROJECT_ID/nsm-streamlit:latest'
