function Spots = makeSpotTable(Detections)

    Spots = table( ...
        (1:Detections.nDetections).', ...
        Detections.frame, ...
        Detections.position,  ...
        Detections.position_refined, ...
        Detections.intensity, ...
        Detections.contrast, ...
        Detections.snr, ...
        VariableNames=["spot_id", "frame", "position", "position_refined", "intensity", "contrast", "snr"] );

        % Detections.noise_std*ones(Detections.nDetections,1),...
        % VariableNames=["spot_id", "frame", "position", "position_refined", "intensity", "contrast", "snr", "noise_std"] );
        
end