function mean_snr = getMeanSnr(R, Kt, sigma_x, spaceFilter, ...
    timeFilter, sigma_t, nonLinearFilter, pfa, localMinRange)

    X = preprocessing(R, Kt=Kt);

    Y = denoising(X, ...
        sigma_x=sigma_x, ...
        spaceFilter=spaceFilter, ...
        timeFilter=timeFilter, ...
        sigma_t=sigma_t, ...
        nonLinearFilter=nonLinearFilter);

    Detections = detection(Y, pfa=pfa, localMinRange=localMinRange);

    mean_snr = -mean(Detections.snr);

end