function TT = makeTrackletTable(Tracklets)

    TT = table( ...
        (1:Tracklets.nTracks).', ...
        (cellfun(@length,Tracklets.spot_ids)).', ...
        (cellfun(@(x) x(1),Tracklets.spot_ids)).', ...
        (cellfun(@(x) x(end),Tracklets.spot_ids)).', ...
        (cellfun(@(x) x(1),Tracklets.positions_refined)).', ...
        (cellfun(@(x) x(end),Tracklets.positions_refined)).', ...
        (cellfun(@(x) x(1),Tracklets.frames)).', ...
        (cellfun(@(x) x(end),Tracklets.frames)).', ...
        Tracklets.spot_ids.',...
        VariableNames=["tracklet_id", "length", "start_spot_id", "end_spot_id", "start_position_refined", "end_position_refined", ...
        "start_frame", "end_frame", "spot_ids"]);

end

% (cellfun(@(x) x(1),Tracklets.positions)).', ...
% (cellfun(@(x) x(end),Tracklets.positions)).', ...