function ET = makeEdgeTable(Edges)

    ET = table( ...
        (1:Edges.nEdges).', ...
        Edges.source_frame, ...
        Edges.source_spot_id, ...
        Edges.target_spot_id, ...
        Edges.jump_distance, ...
        VariableNames=["edge_id", "source_frame", "source_spot_id", "target_spot_id", "jump_distance"] );

end